plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services' // Plugin untuk baca google-services.json
}

android {
    // Namespace internal (lokasi folder code)
    namespace 'com.nataedu'
    compileSdk 34

    defaultConfig {
        // DISAMAKAN dengan package_name yang ada di JSON kamu
        applicationId "com.nataedu"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }


}

dependencies {
    // UI Libraries
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.activity:activity:1.8.2'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'

    // Firebase BoM (Versi 32.7.0 sesuai file lamamu)
    implementation platform('com.google.firebase:firebase-bom:32.7.0')

    // LIBRARY UTAMA UNTUK LOGIN & DATABASE
    implementation 'com.google.firebase:firebase-auth'      // Untuk Login/Register
    implementation 'com.google.firebase:firebase-firestore' // Untuk Database (Simpan Profil)

    // Test Libraries
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}